theme: jekyll-theme-cayman

title: Automatic Music Transcription and Instrument Transposition with Differentiable Rendering
description: Hosting additional materials for The 2020 Joint Conference on AI Music Creativity.
