theme: jekyll-theme-minimal
title: AUTOMATIC MUSIC TRANSCRIPTION USING SPECTRAL LOSS AND ITS APPLICATION FOR AUTOMATIC MUSIC TIMBRE-BASED ARRANGEMENT
description: Additional materials for the submission to ISMIR 2020.
